# Generated by Django 3.1 on 2020-08-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='-', max_length=100)),
                ('email', models.CharField(default='-', max_length=100)),
                ('grade', models.FloatField(default=0.0)),
            ],
        ),
    ]
