# Generated by Django 3.1 on 2020-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davematthews', '0002_frqassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.CreateModel(
            name='WsAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=100)),
                ('total_points', models.IntegerField(default=10)),
                ('answers', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='frqassignment',
            name='title',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
