# Generated by Django 3.1 on 2020-08-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davematthews', '0004_auto_20200811_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='content',
            field=models.TextField(default='-'),
        ),
    ]
