# Generated by Django 3.1 on 2020-08-11 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('davematthews', '0006_auto_20200811_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='frqassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7e1c6b97-6e7b-4e46-8a75-16834af66419')),
        ),
        migrations.AddField(
            model_name='frqsubmission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d6c1b45-2136-4836-a87f-5f0b380b5bc8')),
        ),
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('63496bea-13a2-4599-8b8f-583b019af8fc')),
        ),
        migrations.AddField(
            model_name='submission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bf3aee0b-cafc-4465-ac27-a3ed1ca898f9')),
        ),
        migrations.AddField(
            model_name='wsassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('67e65925-d464-45bf-94d5-41367604cded')),
        ),
    ]
