# Generated by Django 3.1 on 2020-08-11 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('davematthews', '0007_auto_20200811_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cb4309b1-b77a-4e14-83bd-7bc6d4c06241')),
        ),
        migrations.AlterField(
            model_name='frqsubmission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('59e88bf7-c130-48a7-9292-dd3957a1eba3')),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d458fe55-fb60-4f21-885c-f363e923786c')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('663941f1-c632-4d04-ae5f-9e36d2a9c06a')),
        ),
        migrations.AlterField(
            model_name='wsassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bc82cef8-68fb-4663-a04b-49b34420af5c')),
        ),
    ]
