# Generated by Django 3.1 on 2020-08-11 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('davematthews', '0008_auto_20200811_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8ba2775d-f94f-4ced-9146-9a634d52c52c')),
        ),
        migrations.AlterField(
            model_name='frqsubmission',
            name='frq',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, to='davematthews.frqassignment'),
        ),
        migrations.AlterField(
            model_name='frqsubmission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('264df8f5-7e8a-4d0b-ae05-28b4e86d0c63')),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7b39dbc3-ec67-498e-ba3f-f9ea11ee4426')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fe1c052f-301d-4455-9840-48295dbfeed4')),
        ),
        migrations.AlterField(
            model_name='wsassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7267a7b8-f4a6-4b68-b7bb-82d7c910048c')),
        ),
    ]
