# Generated by Django 3.1 on 2020-08-11 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('davematthews', '0009_auto_20200811_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('47782687-b6a4-43ce-beeb-c4dc8c3b0a23')),
        ),
        migrations.AlterField(
            model_name='frqsubmission',
            name='frq',
            field=models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.CASCADE, to='davematthews.frqassignment'),
        ),
        migrations.AlterField(
            model_name='frqsubmission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('40d79379-83bd-407e-9593-c96bd6c66e2a')),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d7667e8-410a-4b30-a4dd-d0b8287c162d')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9fcfe483-1295-4994-93d0-a2d06f6c2761')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ws',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE, to='davematthews.wsassignment'),
        ),
        migrations.AlterField(
            model_name='wsassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fbb795cc-da41-4108-a0f4-98114cb918f3')),
        ),
    ]
